### ISSUE TITLE
Tag match rule type for filter

### ISSUE THREAD

**Issue by mjs** [jumptrading/influx-spout#90]
Experiment with a filter rule type that matches on a specific value of a specific tag. This is potentially a faster and safer way to match lines that would negate the need for regex matching in many cases.

This relates to #56.

**Comment by oplehto** [comment]
Initially matching against a single tag would be great but ultimately we should have support for matching multiple tags. I foresee that this kind of requirement will emerge and setting up regex-based matching is difficult as we can't assume the tags are arriving in a certain order. Even if there is some performance tradeoff, the simplicity of configuration is a win.

**Comment by mjs** [comment]
No worries. That should be easy enough to accommodate without hurting performance too much.

How would you like to configuration to look?

Without adding new fields to the current config we could do something like this:

```toml
[[rule]]
type = "tags"
match = "foo=thing and bar=other"
subject = "somewhere"
```

but that steps around TOML somewhat.

Some viable alternatives:

```toml
[[rule]]
type = "tags"
tags = ["foo=thing", "bar=other"]
subject = "somewhere"
```

```toml
[[rule]]
type = "tags"
tags = [
  ["foo", "thing"],
  ["bar", "other"],
]
subject = "somewhere"
```

The new config validation feature could be extended to ensure `tags` is appropriately structured and `tags` is only used if `type` is `tags` etc. 

Any preferences?
